version: "2"
run:
  build-tags:
    - linux
    - libsqlite3
    - sqlite_fts5
  issues-exit-code: 0
  tests: false
linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - containedctx
    - dupl
    - durationcheck
    - gosec
    - makezero
    - noctx
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - sqlclosecheck
    - unparam
    - unparam
  settings:
    dupl:
      threshold: 125
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
