// Code generated by 'yaegi extract go.goblog.app/app/pkgs/plugintypes'. DO NOT EDIT.

// MIT License
//
// Copyright (c) 2020 - 2023 Jan-Lukas Else
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package yaegiwrappers

import (
	"context"
	"database/sql"
	"github.com/PuerkitoBio/goquery"
	"go.goblog.app/app/pkgs/plugintypes"
	"io"
	"net/http"
	"reflect"
)

func init() {
	Symbols["go.goblog.app/app/pkgs/plugintypes/plugintypes"] = map[string]reflect.Value{
		// type definitions
		"App":             reflect.ValueOf((*plugintypes.App)(nil)),
		"Blog":            reflect.ValueOf((*plugintypes.Blog)(nil)),
		"Database":        reflect.ValueOf((*plugintypes.Database)(nil)),
		"Exec":            reflect.ValueOf((*plugintypes.Exec)(nil)),
		"Middleware":      reflect.ValueOf((*plugintypes.Middleware)(nil)),
		"Post":            reflect.ValueOf((*plugintypes.Post)(nil)),
		"PostCreatedHook": reflect.ValueOf((*plugintypes.PostCreatedHook)(nil)),
		"PostDeletedHook": reflect.ValueOf((*plugintypes.PostDeletedHook)(nil)),
		"PostUpdatedHook": reflect.ValueOf((*plugintypes.PostUpdatedHook)(nil)),
		"RenderContext":   reflect.ValueOf((*plugintypes.RenderContext)(nil)),
		"SetApp":          reflect.ValueOf((*plugintypes.SetApp)(nil)),
		"SetConfig":       reflect.ValueOf((*plugintypes.SetConfig)(nil)),
		"UI":              reflect.ValueOf((*plugintypes.UI)(nil)),
		"UI2":             reflect.ValueOf((*plugintypes.UI2)(nil)),
		"UIFooter":        reflect.ValueOf((*plugintypes.UIFooter)(nil)),
		"UIPost":          reflect.ValueOf((*plugintypes.UIPost)(nil)),
		"UISummary":       reflect.ValueOf((*plugintypes.UISummary)(nil)),

		// interface wrapper definitions
		"_App":             reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_App)(nil)),
		"_Blog":            reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_Blog)(nil)),
		"_Database":        reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_Database)(nil)),
		"_Exec":            reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_Exec)(nil)),
		"_Middleware":      reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_Middleware)(nil)),
		"_Post":            reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_Post)(nil)),
		"_PostCreatedHook": reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_PostCreatedHook)(nil)),
		"_PostDeletedHook": reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_PostDeletedHook)(nil)),
		"_PostUpdatedHook": reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_PostUpdatedHook)(nil)),
		"_RenderContext":   reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_RenderContext)(nil)),
		"_SetApp":          reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_SetApp)(nil)),
		"_SetConfig":       reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_SetConfig)(nil)),
		"_UI":              reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_UI)(nil)),
		"_UI2":             reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_UI2)(nil)),
		"_UIFooter":        reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_UIFooter)(nil)),
		"_UIPost":          reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_UIPost)(nil)),
		"_UISummary":       reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_UISummary)(nil)),
	}
}

// _go_goblog_app_app_pkgs_plugintypes_App is an interface wrapper for App type
type _go_goblog_app_app_pkgs_plugintypes_App struct {
	IValue                interface{}
	WAssetPath            func(filename string) string
	WCompileAsset         func(filename string, reader io.Reader) error
	WGetBlog              func(name string) (plugintypes.Blog, bool)
	WGetDatabase          func() plugintypes.Database
	WGetHTTPClient        func() *http.Client
	WGetPost              func(path string) (plugintypes.Post, error)
	WPurgeCache           func()
	WRenderMarkdownAsText func(markdown string) (text string, err error)
	WSetPostParameter     func(path string, parameter string, values []string) error
}

func (W _go_goblog_app_app_pkgs_plugintypes_App) AssetPath(filename string) string {
	return W.WAssetPath(filename)
}
func (W _go_goblog_app_app_pkgs_plugintypes_App) CompileAsset(filename string, reader io.Reader) error {
	return W.WCompileAsset(filename, reader)
}
func (W _go_goblog_app_app_pkgs_plugintypes_App) GetBlog(name string) (plugintypes.Blog, bool) {
	return W.WGetBlog(name)
}
func (W _go_goblog_app_app_pkgs_plugintypes_App) GetDatabase() plugintypes.Database {
	return W.WGetDatabase()
}
func (W _go_goblog_app_app_pkgs_plugintypes_App) GetHTTPClient() *http.Client {
	return W.WGetHTTPClient()
}
func (W _go_goblog_app_app_pkgs_plugintypes_App) GetPost(path string) (plugintypes.Post, error) {
	return W.WGetPost(path)
}
func (W _go_goblog_app_app_pkgs_plugintypes_App) PurgeCache() {
	W.WPurgeCache()
}
func (W _go_goblog_app_app_pkgs_plugintypes_App) RenderMarkdownAsText(markdown string) (text string, err error) {
	return W.WRenderMarkdownAsText(markdown)
}
func (W _go_goblog_app_app_pkgs_plugintypes_App) SetPostParameter(path string, parameter string, values []string) error {
	return W.WSetPostParameter(path, parameter, values)
}

// _go_goblog_app_app_pkgs_plugintypes_Blog is an interface wrapper for Blog type
type _go_goblog_app_app_pkgs_plugintypes_Blog struct {
	IValue       interface{}
	WGetLanguage func() string
}

func (W _go_goblog_app_app_pkgs_plugintypes_Blog) GetLanguage() string {
	return W.WGetLanguage()
}

// _go_goblog_app_app_pkgs_plugintypes_Database is an interface wrapper for Database type
type _go_goblog_app_app_pkgs_plugintypes_Database struct {
	IValue           interface{}
	WExec            func(a0 string, a1 ...any) (sql.Result, error)
	WExecContext     func(a0 context.Context, a1 string, a2 ...any) (sql.Result, error)
	WQuery           func(a0 string, a1 ...any) (*sql.Rows, error)
	WQueryContext    func(a0 context.Context, a1 string, a2 ...any) (*sql.Rows, error)
	WQueryRow        func(a0 string, a1 ...any) (*sql.Row, error)
	WQueryRowContext func(a0 context.Context, a1 string, a2 ...any) (*sql.Row, error)
}

func (W _go_goblog_app_app_pkgs_plugintypes_Database) Exec(a0 string, a1 ...any) (sql.Result, error) {
	return W.WExec(a0, a1...)
}
func (W _go_goblog_app_app_pkgs_plugintypes_Database) ExecContext(a0 context.Context, a1 string, a2 ...any) (sql.Result, error) {
	return W.WExecContext(a0, a1, a2...)
}
func (W _go_goblog_app_app_pkgs_plugintypes_Database) Query(a0 string, a1 ...any) (*sql.Rows, error) {
	return W.WQuery(a0, a1...)
}
func (W _go_goblog_app_app_pkgs_plugintypes_Database) QueryContext(a0 context.Context, a1 string, a2 ...any) (*sql.Rows, error) {
	return W.WQueryContext(a0, a1, a2...)
}
func (W _go_goblog_app_app_pkgs_plugintypes_Database) QueryRow(a0 string, a1 ...any) (*sql.Row, error) {
	return W.WQueryRow(a0, a1...)
}
func (W _go_goblog_app_app_pkgs_plugintypes_Database) QueryRowContext(a0 context.Context, a1 string, a2 ...any) (*sql.Row, error) {
	return W.WQueryRowContext(a0, a1, a2...)
}

// _go_goblog_app_app_pkgs_plugintypes_Exec is an interface wrapper for Exec type
type _go_goblog_app_app_pkgs_plugintypes_Exec struct {
	IValue interface{}
	WExec  func()
}

func (W _go_goblog_app_app_pkgs_plugintypes_Exec) Exec() {
	W.WExec()
}

// _go_goblog_app_app_pkgs_plugintypes_Middleware is an interface wrapper for Middleware type
type _go_goblog_app_app_pkgs_plugintypes_Middleware struct {
	IValue   interface{}
	WHandler func(next http.Handler) http.Handler
	WPrio    func() int
}

func (W _go_goblog_app_app_pkgs_plugintypes_Middleware) Handler(next http.Handler) http.Handler {
	return W.WHandler(next)
}
func (W _go_goblog_app_app_pkgs_plugintypes_Middleware) Prio() int {
	return W.WPrio()
}

// _go_goblog_app_app_pkgs_plugintypes_Post is an interface wrapper for Post type
type _go_goblog_app_app_pkgs_plugintypes_Post struct {
	IValue                  interface{}
	WGetBlog                func() string
	WGetContent             func() string
	WGetFirstParameterValue func(parameter string) string
	WGetParameter           func(parameter string) []string
	WGetParameters          func() map[string][]string
	WGetPath                func() string
	WGetPublished           func() string
	WGetSection             func() string
	WGetTitle               func() string
	WGetUpdated             func() string
}

func (W _go_goblog_app_app_pkgs_plugintypes_Post) GetBlog() string {
	return W.WGetBlog()
}
func (W _go_goblog_app_app_pkgs_plugintypes_Post) GetContent() string {
	return W.WGetContent()
}
func (W _go_goblog_app_app_pkgs_plugintypes_Post) GetFirstParameterValue(parameter string) string {
	return W.WGetFirstParameterValue(parameter)
}
func (W _go_goblog_app_app_pkgs_plugintypes_Post) GetParameter(parameter string) []string {
	return W.WGetParameter(parameter)
}
func (W _go_goblog_app_app_pkgs_plugintypes_Post) GetParameters() map[string][]string {
	return W.WGetParameters()
}
func (W _go_goblog_app_app_pkgs_plugintypes_Post) GetPath() string {
	return W.WGetPath()
}
func (W _go_goblog_app_app_pkgs_plugintypes_Post) GetPublished() string {
	return W.WGetPublished()
}
func (W _go_goblog_app_app_pkgs_plugintypes_Post) GetSection() string {
	return W.WGetSection()
}
func (W _go_goblog_app_app_pkgs_plugintypes_Post) GetTitle() string {
	return W.WGetTitle()
}
func (W _go_goblog_app_app_pkgs_plugintypes_Post) GetUpdated() string {
	return W.WGetUpdated()
}

// _go_goblog_app_app_pkgs_plugintypes_PostCreatedHook is an interface wrapper for PostCreatedHook type
type _go_goblog_app_app_pkgs_plugintypes_PostCreatedHook struct {
	IValue       interface{}
	WPostCreated func(post plugintypes.Post)
}

func (W _go_goblog_app_app_pkgs_plugintypes_PostCreatedHook) PostCreated(post plugintypes.Post) {
	W.WPostCreated(post)
}

// _go_goblog_app_app_pkgs_plugintypes_PostDeletedHook is an interface wrapper for PostDeletedHook type
type _go_goblog_app_app_pkgs_plugintypes_PostDeletedHook struct {
	IValue       interface{}
	WPostDeleted func(post plugintypes.Post)
}

func (W _go_goblog_app_app_pkgs_plugintypes_PostDeletedHook) PostDeleted(post plugintypes.Post) {
	W.WPostDeleted(post)
}

// _go_goblog_app_app_pkgs_plugintypes_PostUpdatedHook is an interface wrapper for PostUpdatedHook type
type _go_goblog_app_app_pkgs_plugintypes_PostUpdatedHook struct {
	IValue       interface{}
	WPostUpdated func(post plugintypes.Post)
}

func (W _go_goblog_app_app_pkgs_plugintypes_PostUpdatedHook) PostUpdated(post plugintypes.Post) {
	W.WPostUpdated(post)
}

// _go_goblog_app_app_pkgs_plugintypes_RenderContext is an interface wrapper for RenderContext type
type _go_goblog_app_app_pkgs_plugintypes_RenderContext struct {
	IValue   interface{}
	WGetBlog func() string
	WGetPath func() string
	WGetURL  func() string
}

func (W _go_goblog_app_app_pkgs_plugintypes_RenderContext) GetBlog() string {
	return W.WGetBlog()
}
func (W _go_goblog_app_app_pkgs_plugintypes_RenderContext) GetPath() string {
	return W.WGetPath()
}
func (W _go_goblog_app_app_pkgs_plugintypes_RenderContext) GetURL() string {
	return W.WGetURL()
}

// _go_goblog_app_app_pkgs_plugintypes_SetApp is an interface wrapper for SetApp type
type _go_goblog_app_app_pkgs_plugintypes_SetApp struct {
	IValue  interface{}
	WSetApp func(app plugintypes.App)
}

func (W _go_goblog_app_app_pkgs_plugintypes_SetApp) SetApp(app plugintypes.App) {
	W.WSetApp(app)
}

// _go_goblog_app_app_pkgs_plugintypes_SetConfig is an interface wrapper for SetConfig type
type _go_goblog_app_app_pkgs_plugintypes_SetConfig struct {
	IValue     interface{}
	WSetConfig func(config map[string]any)
}

func (W _go_goblog_app_app_pkgs_plugintypes_SetConfig) SetConfig(config map[string]any) {
	W.WSetConfig(config)
}

// _go_goblog_app_app_pkgs_plugintypes_UI is an interface wrapper for UI type
type _go_goblog_app_app_pkgs_plugintypes_UI struct {
	IValue  interface{}
	WRender func(renderContext plugintypes.RenderContext, rendered io.Reader, modified io.Writer)
}

func (W _go_goblog_app_app_pkgs_plugintypes_UI) Render(renderContext plugintypes.RenderContext, rendered io.Reader, modified io.Writer) {
	W.WRender(renderContext, rendered, modified)
}

// _go_goblog_app_app_pkgs_plugintypes_UI2 is an interface wrapper for UI2 type
type _go_goblog_app_app_pkgs_plugintypes_UI2 struct {
	IValue              interface{}
	WRenderWithDocument func(renderContext plugintypes.RenderContext, doc *goquery.Document)
}

func (W _go_goblog_app_app_pkgs_plugintypes_UI2) RenderWithDocument(renderContext plugintypes.RenderContext, doc *goquery.Document) {
	W.WRenderWithDocument(renderContext, doc)
}

// _go_goblog_app_app_pkgs_plugintypes_UIFooter is an interface wrapper for UIFooter type
type _go_goblog_app_app_pkgs_plugintypes_UIFooter struct {
	IValue        interface{}
	WRenderFooter func(renderContext plugintypes.RenderContext, doc *goquery.Document)
}

func (W _go_goblog_app_app_pkgs_plugintypes_UIFooter) RenderFooter(renderContext plugintypes.RenderContext, doc *goquery.Document) {
	W.WRenderFooter(renderContext, doc)
}

// _go_goblog_app_app_pkgs_plugintypes_UIPost is an interface wrapper for UIPost type
type _go_goblog_app_app_pkgs_plugintypes_UIPost struct {
	IValue      interface{}
	WRenderPost func(renderContext plugintypes.RenderContext, post plugintypes.Post, doc *goquery.Document)
}

func (W _go_goblog_app_app_pkgs_plugintypes_UIPost) RenderPost(renderContext plugintypes.RenderContext, post plugintypes.Post, doc *goquery.Document) {
	W.WRenderPost(renderContext, post, doc)
}

// _go_goblog_app_app_pkgs_plugintypes_UISummary is an interface wrapper for UISummary type
type _go_goblog_app_app_pkgs_plugintypes_UISummary struct {
	IValue                interface{}
	WRenderSummaryForPost func(renderContext plugintypes.RenderContext, post plugintypes.Post, doc *goquery.Document)
}

func (W _go_goblog_app_app_pkgs_plugintypes_UISummary) RenderSummaryForPost(renderContext plugintypes.RenderContext, post plugintypes.Post, doc *goquery.Document) {
	W.WRenderSummaryForPost(renderContext, post, doc)
}
