// Code generated by 'yaegi extract go.goblog.app/app/pkgs/plugintypes'. DO NOT EDIT.

// MIT License
//
// Copyright (c) 2020 - 2022 Jan-Lukas Else
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

package yaegiwrappers

import (
	"context"
	"database/sql"
	"go.goblog.app/app/pkgs/htmlbuilder"
	"go.goblog.app/app/pkgs/plugintypes"
	"net/http"
	"reflect"
)

func init() {
	Symbols["go.goblog.app/app/pkgs/plugintypes/plugintypes"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BlogFooterRenderType":      reflect.ValueOf(plugintypes.BlogFooterRenderType),
		"PostMainElementRenderType": reflect.ValueOf(plugintypes.PostMainElementRenderType),

		// type definitions
		"App":            reflect.ValueOf((*plugintypes.App)(nil)),
		"Blog":           reflect.ValueOf((*plugintypes.Blog)(nil)),
		"BlogRenderData": reflect.ValueOf((*plugintypes.BlogRenderData)(nil)),
		"Database":       reflect.ValueOf((*plugintypes.Database)(nil)),
		"Exec":           reflect.ValueOf((*plugintypes.Exec)(nil)),
		"Middleware":     reflect.ValueOf((*plugintypes.Middleware)(nil)),
		"Post":           reflect.ValueOf((*plugintypes.Post)(nil)),
		"PostRenderData": reflect.ValueOf((*plugintypes.PostRenderData)(nil)),
		"RenderData":     reflect.ValueOf((*plugintypes.RenderData)(nil)),
		"RenderNextFunc": reflect.ValueOf((*plugintypes.RenderNextFunc)(nil)),
		"RenderType":     reflect.ValueOf((*plugintypes.RenderType)(nil)),
		"SetApp":         reflect.ValueOf((*plugintypes.SetApp)(nil)),
		"SetConfig":      reflect.ValueOf((*plugintypes.SetConfig)(nil)),
		"UI":             reflect.ValueOf((*plugintypes.UI)(nil)),

		// interface wrapper definitions
		"_App":            reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_App)(nil)),
		"_Blog":           reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_Blog)(nil)),
		"_BlogRenderData": reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_BlogRenderData)(nil)),
		"_Database":       reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_Database)(nil)),
		"_Exec":           reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_Exec)(nil)),
		"_Middleware":     reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_Middleware)(nil)),
		"_Post":           reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_Post)(nil)),
		"_PostRenderData": reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_PostRenderData)(nil)),
		"_RenderData":     reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_RenderData)(nil)),
		"_SetApp":         reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_SetApp)(nil)),
		"_SetConfig":      reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_SetConfig)(nil)),
		"_UI":             reflect.ValueOf((*_go_goblog_app_app_pkgs_plugintypes_UI)(nil)),
	}
}

// _go_goblog_app_app_pkgs_plugintypes_App is an interface wrapper for App type
type _go_goblog_app_app_pkgs_plugintypes_App struct {
	IValue       interface{}
	WGetDatabase func() plugintypes.Database
}

func (W _go_goblog_app_app_pkgs_plugintypes_App) GetDatabase() plugintypes.Database {
	return W.WGetDatabase()
}

// _go_goblog_app_app_pkgs_plugintypes_Blog is an interface wrapper for Blog type
type _go_goblog_app_app_pkgs_plugintypes_Blog struct {
	IValue   interface{}
	WGetBlog func() string
}

func (W _go_goblog_app_app_pkgs_plugintypes_Blog) GetBlog() string {
	return W.WGetBlog()
}

// _go_goblog_app_app_pkgs_plugintypes_BlogRenderData is an interface wrapper for BlogRenderData type
type _go_goblog_app_app_pkgs_plugintypes_BlogRenderData struct {
	IValue   interface{}
	WGetBlog func() plugintypes.Blog
}

func (W _go_goblog_app_app_pkgs_plugintypes_BlogRenderData) GetBlog() plugintypes.Blog {
	return W.WGetBlog()
}

// _go_goblog_app_app_pkgs_plugintypes_Database is an interface wrapper for Database type
type _go_goblog_app_app_pkgs_plugintypes_Database struct {
	IValue           interface{}
	WExec            func(a0 string, a1 ...any) (sql.Result, error)
	WExecContext     func(a0 context.Context, a1 string, a2 ...any) (sql.Result, error)
	WQuery           func(a0 string, a1 ...any) (*sql.Rows, error)
	WQueryContext    func(a0 context.Context, a1 string, a2 ...any) (*sql.Rows, error)
	WQueryRow        func(a0 string, a1 ...any) (*sql.Row, error)
	WQueryRowContext func(a0 context.Context, a1 string, a2 ...any) (*sql.Row, error)
}

func (W _go_goblog_app_app_pkgs_plugintypes_Database) Exec(a0 string, a1 ...any) (sql.Result, error) {
	return W.WExec(a0, a1...)
}
func (W _go_goblog_app_app_pkgs_plugintypes_Database) ExecContext(a0 context.Context, a1 string, a2 ...any) (sql.Result, error) {
	return W.WExecContext(a0, a1, a2...)
}
func (W _go_goblog_app_app_pkgs_plugintypes_Database) Query(a0 string, a1 ...any) (*sql.Rows, error) {
	return W.WQuery(a0, a1...)
}
func (W _go_goblog_app_app_pkgs_plugintypes_Database) QueryContext(a0 context.Context, a1 string, a2 ...any) (*sql.Rows, error) {
	return W.WQueryContext(a0, a1, a2...)
}
func (W _go_goblog_app_app_pkgs_plugintypes_Database) QueryRow(a0 string, a1 ...any) (*sql.Row, error) {
	return W.WQueryRow(a0, a1...)
}
func (W _go_goblog_app_app_pkgs_plugintypes_Database) QueryRowContext(a0 context.Context, a1 string, a2 ...any) (*sql.Row, error) {
	return W.WQueryRowContext(a0, a1, a2...)
}

// _go_goblog_app_app_pkgs_plugintypes_Exec is an interface wrapper for Exec type
type _go_goblog_app_app_pkgs_plugintypes_Exec struct {
	IValue     interface{}
	WExec      func()
	WSetApp    func(a0 plugintypes.App)
	WSetConfig func(a0 map[string]any)
}

func (W _go_goblog_app_app_pkgs_plugintypes_Exec) Exec() {
	W.WExec()
}
func (W _go_goblog_app_app_pkgs_plugintypes_Exec) SetApp(a0 plugintypes.App) {
	W.WSetApp(a0)
}
func (W _go_goblog_app_app_pkgs_plugintypes_Exec) SetConfig(a0 map[string]any) {
	W.WSetConfig(a0)
}

// _go_goblog_app_app_pkgs_plugintypes_Middleware is an interface wrapper for Middleware type
type _go_goblog_app_app_pkgs_plugintypes_Middleware struct {
	IValue     interface{}
	WHandler   func(a0 http.Handler) http.Handler
	WPrio      func() int
	WSetApp    func(a0 plugintypes.App)
	WSetConfig func(a0 map[string]any)
}

func (W _go_goblog_app_app_pkgs_plugintypes_Middleware) Handler(a0 http.Handler) http.Handler {
	return W.WHandler(a0)
}
func (W _go_goblog_app_app_pkgs_plugintypes_Middleware) Prio() int {
	return W.WPrio()
}
func (W _go_goblog_app_app_pkgs_plugintypes_Middleware) SetApp(a0 plugintypes.App) {
	W.WSetApp(a0)
}
func (W _go_goblog_app_app_pkgs_plugintypes_Middleware) SetConfig(a0 map[string]any) {
	W.WSetConfig(a0)
}

// _go_goblog_app_app_pkgs_plugintypes_Post is an interface wrapper for Post type
type _go_goblog_app_app_pkgs_plugintypes_Post struct {
	IValue         interface{}
	WGetParameters func() map[string][]string
}

func (W _go_goblog_app_app_pkgs_plugintypes_Post) GetParameters() map[string][]string {
	return W.WGetParameters()
}

// _go_goblog_app_app_pkgs_plugintypes_PostRenderData is an interface wrapper for PostRenderData type
type _go_goblog_app_app_pkgs_plugintypes_PostRenderData struct {
	IValue   interface{}
	WGetPost func() plugintypes.Post
}

func (W _go_goblog_app_app_pkgs_plugintypes_PostRenderData) GetPost() plugintypes.Post {
	return W.WGetPost()
}

// _go_goblog_app_app_pkgs_plugintypes_RenderData is an interface wrapper for RenderData type
type _go_goblog_app_app_pkgs_plugintypes_RenderData struct {
	IValue interface{}
}

// _go_goblog_app_app_pkgs_plugintypes_SetApp is an interface wrapper for SetApp type
type _go_goblog_app_app_pkgs_plugintypes_SetApp struct {
	IValue  interface{}
	WSetApp func(a0 plugintypes.App)
}

func (W _go_goblog_app_app_pkgs_plugintypes_SetApp) SetApp(a0 plugintypes.App) {
	W.WSetApp(a0)
}

// _go_goblog_app_app_pkgs_plugintypes_SetConfig is an interface wrapper for SetConfig type
type _go_goblog_app_app_pkgs_plugintypes_SetConfig struct {
	IValue     interface{}
	WSetConfig func(a0 map[string]any)
}

func (W _go_goblog_app_app_pkgs_plugintypes_SetConfig) SetConfig(a0 map[string]any) {
	W.WSetConfig(a0)
}

// _go_goblog_app_app_pkgs_plugintypes_UI is an interface wrapper for UI type
type _go_goblog_app_app_pkgs_plugintypes_UI struct {
	IValue     interface{}
	WRender    func(a0 *htmlbuilder.HtmlBuilder, a1 plugintypes.RenderType, a2 plugintypes.RenderData, a3 plugintypes.RenderNextFunc)
	WSetApp    func(a0 plugintypes.App)
	WSetConfig func(a0 map[string]any)
}

func (W _go_goblog_app_app_pkgs_plugintypes_UI) Render(a0 *htmlbuilder.HtmlBuilder, a1 plugintypes.RenderType, a2 plugintypes.RenderData, a3 plugintypes.RenderNextFunc) {
	W.WRender(a0, a1, a2, a3)
}
func (W _go_goblog_app_app_pkgs_plugintypes_UI) SetApp(a0 plugintypes.App) {
	W.WSetApp(a0)
}
func (W _go_goblog_app_app_pkgs_plugintypes_UI) SetConfig(a0 map[string]any) {
	W.WSetConfig(a0)
}
