acommentby: "A comment by"
addlikecontextdesc: "Automatically add like context to new posts with a like link and no manually set like title."
addliketitledesc: "Automatically add like title to new posts with a like link and no manually set like title."
addreplycontextdesc: "Automatically add reply context to new posts with a reply link and no manually set reply title."
addreplytitledesc: "Automatically add reply title to new posts with a reply link and no manually set reply title."
apfollower: "Follower"
apfollowers: "ActivityPub followers"
apinbox: "Inbox"
approve: "Approve"
approved: "Approved"
authenticate: "Authenticate"
captchainstructions: "Please enter the digits from the image above"
changevisibility-private: "Make private"
changevisibility-public: "Make public"
changevisibility-unlisted: "Make unlisted"
chars: "Characters"
comment: "Comment"
comments: "Comments"
confirmdelete: "Confirm deletion"
connectedviator: "Connected via Tor."
connectviator: "Connect via Tor."
contactagreesend: "Accept & Send"
contactsend: "Send"
create: "Create"
default: "Default"
delete: "Delete"
deleteall: "Delete all"
deletedposts: "Deleted posts"
deletedpostsdesc: "Deleted posts that will be permanently deleted after 7 days."
deletepasskey: "Delete Passkey"
docomment: "Comment"
donotsetupdated: "Do not change the update timestamp"
download: "Download"
drafts: "Drafts"
draftsdesc: "Posts with status `draft`."
edit: "Edit"
editcommenttitle: "Edit comment"
editor: "Editor"
editorpostdesc: "💡 Empty parameters are automatically removed, parameters prefixed with \"+\" (e.g. +images: ...) are appended to existing parameters. More possible parameters: %s. Possible states for `%s` and `%s`: %s and %s."
editorusetemplate: "Use template"
emailopt: "Email (optional)"
feed: "Feed"
fileuses: "File uses"
follow: "Follow"
followusingactivitypub: "Follow using ActivityPub"
general: "General"
gentts: "Generate Text-To-Speech audio"
gpxhelper: "GPX helper"
gpxhelperdesc: "💡 Minify GPX and generate YAML for the frontmatter."
hideoldcontentwarningdesc: "Hide the warning for old posts (older than 1 year)"
hidesharebuttondesc: "Hide share button for posts"
hidetranslatebuttondesc: "Hide translate button for posts"
indieauth: "IndieAuth"
interactions: "Interactions & Comments"
interactionslabel: "Have you published a response to this? Paste the URL here."
kilometers: "kilometers"
likeof: "Like of"
loading: "Loading..."
location: "Location"
locationfailed: "Failed to request the location"
locationget: "Request location"
locationnotsupported: "The location API is not supported by this browser"
login: "Login"
loginpasskey: "Login with Passkey"
logout: "Logout"
mediafiles: "Media files"
message: "Message"
messagesent: "Message sent"
meters: "meters"
nameopt: "Name (optional)"
next: "Next"
nofiles: "No files"
nolocations: "No posts with locations"
noposts: "There are no posts here."
notifications: "Notifications"
oldcontent: "⚠️ This entry is already over one year old. It may no longer be up to date. Opinions may have changed."
passkey: "Passkey"
password: "Password"
pinned: "Pinned"
posts: "Posts"
postsections: "Post sections"
prev: "Previous"
privateposts: "Private posts"
privatepostsdesc: "Published posts with visibility `private` that are visible only when logged in."
profileimage: "Profile image"
publishedon: "Published on"
registerupdatepasskey: "Register or update Passkey"
replyto: "Reply to"
reverify: "Reverify"
scheduledposts: "Scheduled posts"
scheduledpostsdesc: "Posts with status `scheduled` that are published when the `published` date is reached."
scopes: "Scopes"
search: "Search"
sectiondescription: "Description"
sectionhideonstart: "Hide on main index"
sectionname: "Name"
sectionpathtemplate: "Path template"
sectionshowfull: "Show full content in summary"
sectiontitle: "Title"
send: "Send (to review)"
settings: "Settings"
settingsusername: "Full user name"
settingsusernick: "User nickname (login username)"
share: "Share online"
shorturl: "Short link:"
speak: "Read aloud"
status: "Status"
stopspeak: "Stop reading aloud"
submit: "Submit"
total: "Total"
totp: "TOTP"
translate: "Translate"
translations: "Translations"
undelete: "Undelete"
unlistedposts: "Unlisted posts"
unlistedpostsdesc: "Published posts with visibility `unlisted` that are not displayed in archives."
update: "Update"
updatedon: "Updated on"
upload: "Upload"
user: "User"
username: "Username"
verified: "Verified"
view: "View"
visibility: "Visibility"
webmentions: "Webmentions"
websiteopt: "Website (optional)"
whatistor: "What is Tor?"
withoutdate: "Without date"
words: "Words"
wordsperpost: "Words per post"
year: "Year"