acommentby: "A comment by"
addlikecontextdesc: "Automatically add like context to new posts with a like link and no manually set like title."
addliketitledesc: "Automatically add like title to new posts with a like link and no manually set like title."
addreplycontextdesc: "Automatically add reply context to new posts with a reply link and no manually set reply title."
addreplytitledesc: "Automatically add reply title to new posts with a reply link and no manually set reply title."
apfollower: "Follower"
apfollowers: "ActivityPub followers"
apinbox: "Inbox"
apppasswordcreated: "App Password Created"
apppasswordcreatedfor: "App password created for"
apppasswordname: "App password name"
apppasswords: "App Passwords"
apppasswordsdesc: "App passwords can be used for API access via Basic Authentication. Use any username with the generated password."
apppasswordtoken: "Your new app password (copy it now, it won't be shown again):"
apppasswordwarning: "This password will only be shown once. Make sure to copy it now!"
approve: "Approve"
approved: "Approved"
authenticate: "Authenticate"
backtosettings: "Back to settings"
blogsettings: "Blog"
captchainstructions: "Please enter the digits from the image above"
changevisibility-private: "Make private"
changevisibility-public: "Make public"
changevisibility-unlisted: "Make unlisted"
chars: "Characters"
comment: "Comment"
comments: "Comments"
confirmdelete: "Confirm deletion"
confirmdeletetotp: "Are you sure you want to disable TOTP? This will reduce the security of your account."
confirmpassword: "Confirm new password"
connectedviator: "Connected via Tor."
connectviator: "Connect via Tor."
contactagreesend: "Accept & Send"
contactsend: "Send"
create: "Create"
createapppassword: "Create app password"
default: "Default"
delete: "Delete"
deleteall: "Delete all"
deletedposts: "Deleted posts"
deletedpostsdesc: "Deleted posts that will be permanently deleted after 7 days."
deletepassword: "Remove password"
deletetotp: "Disable TOTP"
deprecatedblogconfigwarning: "⚠️ Deprecated blog options (title, description) are still present in your config file. Please remove them and use the settings below."
deprecatedconfigwarning: "⚠️ Deprecated authentication options (password, totp, appPasswords) are still present in your config file. Please remove them."
docomment: "Comment"
donotsetupdated: "Do not change the update timestamp"
download: "Download"
drafts: "Drafts"
draftsdesc: "Posts with status `draft`."
edit: "Edit"
editcommenttitle: "Edit comment"
editor: "Editor"
editorpostdesc: "💡 Empty parameters are automatically removed, parameters prefixed with \"+\" (e.g. +images: ...) are appended to existing parameters. More possible parameters: %s. Possible states for `%s` and `%s`: %s and %s."
editorusetemplate: "Use template"
emailopt: "Email (optional)"
feed: "Feed"
fileuses: "File uses"
follow: "Follow"
followusingactivitypub: "Follow using ActivityPub"
general: "General"
gentts: "Generate Text-To-Speech audio"
gpxhelper: "GPX helper"
gpxhelperdesc: "💡 Minify GPX and generate YAML for the frontmatter."
hideoldcontentwarningdesc: "Hide the warning for old posts (older than 1 year)"
hidesharebuttondesc: "Hide share button for posts"
hidespeakbuttondesc: "Hide read aloud button for posts"
hidetranslatebuttondesc: "Hide translate button for posts"
indieauth: "IndieAuth"
interactions: "Interactions & Comments"
interactionslabel: "Have you published a response to this? Paste the URL here."
kilometers: "kilometers"
likeof: "Like of"
loading: "Loading..."
location: "Location"
locationfailed: "Failed to request the location"
locationget: "Request location"
locationnotsupported: "The location API is not supported by this browser"
login: "Login"
loginpasskey: "Login with Passkey"
logout: "Logout"
mediafiles: "Media files"
message: "Message"
messagesent: "Message sent"
meters: "meters"
nameopt: "Name (optional)"
newpassword: "New password"
next: "Next"
nofiles: "No files"
nolocations: "No posts with locations"
nopasswordset: "No password is set. You need a passkey to log in or set a password below."
noposts: "There are no posts here."
notifications: "Notifications"
oldcontent: "⚠️ This entry is already over one year old. It may no longer be up to date. Opinions may have changed."
passkeys: "Passkeys"
password: "Password"
passwordset: "A password is configured."
pinned: "Pinned"
posts: "Posts"
postsections: "Post sections"
prev: "Previous"
privateposts: "Private posts"
privatepostsdesc: "Published posts with visibility `private` that are visible only when logged in."
profileimage: "Profile image"
publishedon: "Published on"
registerpasskey: "Register new Passkey"
rename: "Rename"
replyto: "Reply to"
reverify: "Reverify"
scheduledposts: "Scheduled posts"
scheduledpostsdesc: "Posts with status `scheduled` that are published when the `published` date is reached."
scopes: "Scopes"
search: "Search"
sectiondescription: "Description"
sectionhideonstart: "Hide on main index"
sectionname: "Name"
sectionpathtemplate: "Path template"
sectionshowfull: "Show full content in summary"
sectiontitle: "Title"
security: "Security"
send: "Send (to review)"
settings: "Settings"
settingsblogdescription: "Blog description (subtitle)"
settingsblogtitle: "Blog title"
settingsusername: "Full user name"
settingsusernick: "User nickname (login username)"
setuptotp: "Enable TOTP"
share: "Share online"
sharecopy: "Copy share text"
sharecopyfeedback: "Copied!"
sharemodalheading: "Share this post"
sharenativeshare: "Use your browser's share dialog"
shorturl: "Short link:"
speak: "Read aloud"
status: "Status"
stopspeak: "Stop reading aloud"
submit: "Submit"
total: "Total"
totp: "TOTP (Two-Factor Authentication)"
totpcode: "TOTP verification code"
totpenabled: "TOTP is enabled."
totpsecret: "TOTP secret"
totpsecretmanual: "Enter this secret in your authenticator app:"
totpsetupinstructions: "Add the secret below to your authenticator app (e.g., Google Authenticator, Authy), then enter the verification code to confirm."
translate: "Translate"
translations: "Translations"
undelete: "Undelete"
unlistedposts: "Unlisted posts"
unlistedpostsdesc: "Published posts with visibility `unlisted` that are not displayed in archives."
update: "Update"
updatedon: "Updated on"
updatepassword: "Update password"
upload: "Upload"
user: "User"
username: "Username"
verified: "Verified"
view: "View"
visibility: "Visibility"
webmentions: "Webmentions"
websiteopt: "Website (optional)"
whatistor: "What is Tor?"
withoutdate: "Without date"
words: "Words"
wordsperpost: "Words per post"
year: "Year"